spring:
  application:
    name: recipes

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    hostname: localhost

server:
  port: 8982

